# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: me@MaedahBatool.com
        MAX_DAYS: 400
        MIN_COMMITS_PER_DAY: 3
        MAX_COMMITS_PER_DAY: 6
