# .github/workflows/main.yml

on:
  schedule:
  - cron: '0 4 * * *' # every day at noon

jobs:
  single-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: me@MaedahBatool.com
        MIN_COMMITS_PER_DAY: 3
        MAX_COMMITS_PER_DAY: 9
